### PR TITLE
Patch amplify endpoint env variable for newer versions

### LINKED ISSUE #7: Amplifylocal fails to update the endpoints with newer versions of Amplify>4.41.0
Tested it based on the communication on our Slack channel.

https://localstack-community.slack.com/archives/CMAFN2KSP/p1669094332036849?thread_ts=1669029187.187949&cid=CMAFN2KSP

```javascript

$ amplifylocal init

Note: It is recommended to run this command from the root of your app directory
? Enter a name for the project awsamplifygraphql
The following configuration will be applied:

Project information
| Name: awsamplifygraphql
| Environment: dev
| Default editor: Visual Studio Code
| App type: javascript
| Javascript framework: react
| Source Directory Path: src
| Distribution Directory Path: build
| Build Command: npm.cmd run-script build
| Start Command: npm.cmd run-script start

? Initialize the project with the above configuration? Yes
Using default provider  awscloudformation
? Select the authentication method you want to use: AWS profile

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

? Please choose the profile you want to use default
🛑 The security token included in the request is invalid.

Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

Session Identifier: ea25816d-f629-4d67-b02a-3a962bb2cd6f
```

### PR DESCRIPTION
**Pull request by pinzon**
This fixes #7. Patching directly the endpoint configuration on the library aws-amplify/cli library doesn't work in newer versions due to the package being an executable. To continue using the cli with Localstack there's the AWS_AMPLIFY_ENDPOINT environment variable.

Changes:
- Patching of AWS_AMPLIFY_ENDPOINT 
- Set default hostname to "localhost.localstack.cloud" 
- Use of HTTPS
- Config option to override generated LocalStack endpoint

### CODE REVIEW

File: lib/index.js [hunk 1]
```diff
@@ -14,7 +14,7 @@ const AWS_SECRET_ACCESS_KEY = 'test';
 const getLocalEndpoint = () => {
   const port = process.env.EDGE_PORT || DEFAULT_EDGE_PORT;
   const host = process.env.LOCALSTACK_HOSTNAME || DEFAULT_HOSTNAME;
-  return `http://${host}:${port}`;
+  return `https://${host}:${port}`;
```
Comment (whummer) [inline lib/index.js]: I think we should introduce a way to override the protocol to be plain `http`, as some users may be facing issues downloading our SSL certificate. 

In fact, might be the easiest if we add a `LOCALSTACK_ENDPOINT` env variable that allows to optionally customize the endpoint URL to connect to (let's also add a hint in the README for it 👍 )

**Review by whummer — APPROVED** [review]
Nice catch! LGTM, only one suggestion regarding customizable endpoint/protocol.

**Comment by whummer** [comment]
Published `amplify-js-local@0.1.8` to npm based on these changes 👍
